### ISSUE TITLE
Need NetworkType: PUBLIC_TEST

### ISSUE THREAD

**Issue by Vijay-Duke** [proximax-storage/java-xpx-chain-sdk#128]

**Comment by tonowie** [comment]
publicTest network type is called TEST_NET. is that what you are looking for? That is standard across all SDKs

**Comment by Vijay-Duke** [comment]
I saw a extra enum in  .cpp and c# libraries that have public_test as one of the network type. With 0x98 hex value. Java sdk does not have it. I was using a online proximax online wallet, which connects to public_test

**Comment by tonowie** [comment]
that is issue in CPP SDK which has not renumbered the network type. Public test network is named TEST_NET
